/* INSURE QUEST | Additional clients (clients 6-18).
 * Same structure as original 5 clients; need of stress events is calibrated automatically by data.ts based on "lower bound of ideal allocation",
 * balance verified by test/balance.test.ts. All scenarios for educational simulation only; coverage cards are functional concepts, not actual products.
 */
import type { CardId, ClientProfile, ChoiceOption, QuestionId, ResKey, Answer, StressEvent } from './types.ts';

const a = (text: string, trust: number, insight: number, key: string | null = null): Answer => ({ text, trust, insight, key });

/** Objection handling four options: link to goal (good) / question (ok) / fear-mongering (bad) / guarantee (bad) */
function objection(text: string, good: [string, string, string], ok: string, fear: string, promise: string): { text: string; options: ChoiceOption[] } {
  return {
    text,
    options: [
      { quality: 'good', text: good[0], title: good[1], body: good[2], changes: { trust: 12, insight: 3, fit: 8, risk: 4 } },
      { quality: 'ok', text: ok, title: '用提問讓客戶自己看見風險', body: '你沒有硬推，把決定權還給客戶；但仍需要把方案和問題連起來。', changes: { trust: 7, insight: 4, fit: 3, risk: 1 } },
      { quality: 'bad', text: fear, title: '恐嚇不是需求教育', body: '用後悔與出事推動成交，會同時傷害信任與合規表達。', changes: { trust: -14, compliance: -20, fit: -4 } },
      { quality: 'bad', text: promise, title: '任何方案都不能保證人生結果', body: '顧問可以說明風險如何被降低，不能承諾報酬或人生目標一定達成。', changes: { trust: -5, compliance: -25, fit: -2 } },
    ],
  };
}

type EvKind = 'income' | 'cash' | 'market';
const ABSORB: Record<EvKind, Partial<Record<ResKey, number>>> = {
  income: { cash: 0.8, protect: 2.0, growth: 0 },
  cash: { cash: 2.2, protect: 0.6, growth: 0 },
  market: { cash: 1.6, protect: 0, growth: -0.5 },
};
/** need initialized to 0, calibrated by data.ts */
function ev(day: number, kind: EvKind, tag: string, title: string, body: string, cards: CardId[], held: string, hit: string): StressEvent {
  return { day, tag, title, body, absorb: ABSORB[kind], cards, need: 0, held, hit };
}

type Ideal = Record<ResKey, [number, number]>;
function client(p: {
  id: string; name: string; short: string; age: number; gender: string; job: string; tag: string; difficulty: string;
  goal: string; amount: string; incomeInfo: string; family: string; intro: string; quote: string;
  facts: [string, string, string][]; answers: Record<QuestionId, Answer>; keyQuestions: QuestionId[];
  ideal: Ideal; cards: Record<CardId, number>; overProtect?: number; overNote?: Partial<Record<CardId, string>>;
  objection: ClientProfile['objection']; stress: StressEvent[];
}): ClientProfile {
  return {
    id: p.id, name: p.name, short: p.short, age: p.age, gender: p.gender, job: p.job, tag: p.tag, difficulty: p.difficulty,
    portrait: p.id, goal: p.goal, amount: p.amount, incomeInfo: p.incomeInfo, family: p.family, intro: p.intro, quote: p.quote,
    facts: p.facts.map(([title, detail, fact]) => ({ title, detail, fact })),
    answers: p.answers, keyQuestions: p.keyQuestions,
    plan: { ideal: p.ideal, cards: p.cards, overProtect: p.overProtect, overNote: p.overNote },
    objection: p.objection, stress: p.stress,
  };
}

export const extraClients: ClientProfile[] = [
  client({
    id: 'junhao', name: '王俊豪', short: '俊豪', age: 32, gender: '男性', job: '外送平台騎手', tag: '零工經濟型', difficulty: '入門',
    goal: '三年內存到開手搖飲店的頭期款', amount: 'NT$ 800,000', incomeInfo: '月收入 4–6 萬，跑越多賺越多', family: '單身，每月給父母 8,000 元',
    intro: '俊豪每天騎車十小時，收入靠趟數累積。他覺得自己身體好、騎車技術好，保險是「出事的人才需要」。',
    quote: '「我騎了五年都沒事，錢先存開店比較實在吧？」',
    facts: [['機車里程表', '一年騎超過六萬公里，雨天也照跑。', '每日高度暴露在交通風險'], ['平台合約', '騎手是承攬關係，沒有勞保以外的公司福利。', '收入中斷沒有雇主保障'], ['開店存摺', '每月固定轉一萬五到開店帳戶。', '三年 80 萬目標資金']],
    answers: {
      income: a('「房租一萬二、給爸媽八千、機車分期四千……停一個月就三萬多要付。」', 8, 13, '收入中斷時的固定支出'),
      goal: a('「開店的錢我絕對不想動，那是我唯一的翻身機會。」', 9, 11, '最不能犧牲的目標'),
      coverage: a('「只有平台幫保的那種，好像只有騎車中才算？我也不太清楚。」', 6, 10, '現有保障缺口'),
      risk: a('「存開店的錢我都放定存，股票我不碰。」', 4, 6, '風險承受度'),
      premium: a('「你是不是想賣我很貴的東西？我一趟才賺幾十塊。」', -9, 1),
    },
    keyQuestions: ['income', 'coverage'],
    ideal: { cash: [3, 4], protect: [4, 5], growth: [1, 3] },
    cards: { accident: 3, income: 3, medical: 2, tools: 1, legacy: -2, care: -2 },
    overNote: { legacy: '俊豪單身，高額家庭責任防線目前不是優先。', care: '32 歲先處理意外與收入中斷，長期照顧可以之後再談。' },
    objection: objection('「我騎車很小心啦，買保險感覺像在詛咒自己。」',
      ['你的小心是真的，所以我們不是預設你會出事；是讓「萬一」發生時，開店的錢不用拿來付房租。', '你尊重他的專業，也守住他的目標', '把保障定位成保護開店資金的防火牆，而不是質疑他的騎車能力。'],
      '如果下雨天在路口被別人撞，休養兩個月，開店計畫會延後多久？',
      '騎車的人十個有九個會出事，你不買以後一定後悔。',
      '買這個方案保證你三年後一定開得成店。'),
    stress: [
      ev(1, 'income', '意外', '雨天被追撞，右腿骨折', '需要休養八週，期間無法接單。', ['accident', 'income'], '意外與收入防線撐住休養期，開店存款沒有動。', '俊豪動用開店存款付房租，計畫延後一年。'),
      ev(20, 'cash', '現金', '機車全損與醫療自費同時到期', '一次需要約七萬元。', ['medical', 'accident'], '預備金吸收了這筆支出。', '只能刷卡分期，利息讓存錢速度變慢。'),
      ev(60, 'market', '市場', '定存利率下調', '存款成長變慢，但本金不受影響。', [], '目標資金穩定，沒有被迫改變計畫。', '他急著把錢轉去高風險商品追報酬。'),
    ],
  }),
  client({
    id: 'meiling', name: '張美玲', short: '美玲', age: 36, gender: '女性', job: '公司行政助理', tag: '單親家長型', difficulty: '進階',
    goal: '讓女兒順利念完大學', amount: 'NT$ 1,200,000', incomeInfo: '月薪 3.6 萬，另有週末家教收入', family: '單親，扶養 8 歲女兒',
    intro: '美玲獨自扶養女兒，預算很緊。她最怕的不是自己生病，而是女兒的生活因此被打亂。',
    quote: '「我每個月都在算錢，真的沒有多餘的預算給保險。」',
    facts: [['女兒的作業簿', '冰箱上貼著女兒的才藝班時間表。', '家中唯一經濟支柱'], ['兩份工作的班表', '平日上班、週末家教，幾乎沒有休息。', '收入來源依賴她的健康'], ['教育基金記帳本', '每月存三千元，目前約十五萬。', '長期教育目標']],
    answers: {
      income: a('「房租、保母、女兒學費……每月兩萬八一定要付，我一倒下就全部停了。」', 9, 13, '收入中斷時的固定支出'),
      goal: a('「女兒的教育不能斷，這是我最在乎的。」', 10, 12, '最不能犧牲的目標'),
      coverage: a('「公司有團保，但我不知道離職或生病請長假時還有沒有。」', 6, 9, '現有保障缺口'),
      risk: a('「我沒辦法承受虧損，存的錢都是女兒的。」', 4, 7, '風險承受度'),
      premium: a('「你一開口就問預算，是不是覺得我付不起？」', -10, 1),
    },
    keyQuestions: ['income', 'goal'],
    ideal: { cash: [4, 5], protect: [4, 5], growth: [1, 2] }, overProtect: 5,
    cards: { legacy: 3, medical: 2, income: 2, accident: 1, care: -2, tools: -2 },
    overNote: { care: '長期照顧不是美玲現在的首要風險。', tools: '美玲沒有營業設備需求。' },
    objection: objection('「預算真的很緊，我是不是先存錢就好？」',
      ['先存錢很重要，所以方案保留了緊急預備；保障這一塊是確保萬一你倒下，女兒的生活與學費有人接住。', '你把保障連回她最在乎的女兒', '尊重預算限制，同時說明保障守住的是她的目標。'],
      '如果你住院一個月，女兒的保母費和學費誰來付？',
      '你不買的話，萬一出事女兒就要流落街頭了。',
      '這個方案保證女兒一定念得完大學。'),
    stress: [
      ev(1, 'income', '收入', '確診需手術，請假兩個月', '兩份收入同時中斷。', ['income', 'medical'], '收入防線讓家中支出照常，女兒的生活沒有改變。', '美玲向親友借錢，教育基金被挪用。'),
      ev(25, 'cash', '現金', '女兒住院與保母費同時到期', '一次需要約六萬元。', ['medical'], '預備金接住了這筆支出。', '只能刷卡周轉，壓力很大。'),
      ev(70, 'income', '家庭', '家庭責任測試：主要照顧者失能', '需要長期安排女兒的生活與教育。', ['legacy'], '家庭責任防線保留了女兒的教育資金。', '女兒的教育計畫被迫中斷。'),
    ],
  }),
  client({
    id: 'jiahao', name: '劉家豪', short: '家豪', age: 31, gender: '男性', job: '軟體工程師', tag: '新手爸媽型', difficulty: '入門',
    goal: '太太育嬰假期間維持家庭生活', amount: 'NT$ 500,000', incomeInfo: '月薪 8 萬，太太育嬰假中', family: '已婚，新生兒 3 個月',
    intro: '家豪剛當爸爸，太太請育嬰假，家裡突然變成單薪。他想把錢都放 ETF 拚資產成長。',
    quote: '「我年輕收入高，應該多投資，保險等小孩大一點再說。」',
    facts: [['嬰兒床', '房間裡堆滿尿布和奶粉。', '新增扶養責任'], ['房貸繳款單', '每月房貸三萬二，還有 25 年。', '長期固定支出'], ['券商 App', '大部分存款都在 ETF。', '資產偏重市場部位']],
    answers: {
      income: a('「房貸三萬二加上小孩開銷，每月至少六萬。現在只有我一份薪水。」', 8, 13, '收入中斷時的固定支出'),
      goal: a('「我最怕的是房子保不住，太太和小孩要搬家。」', 9, 12, '最不能犧牲的目標'),
      coverage: a('「公司有團保，但金額我沒算過，應該不夠付房貸吧。」', 6, 10, '現有保障缺口'),
      risk: a('「ETF 跌三成我也還好，反正長期持有。」', 5, 8, '風險承受度'),
      premium: a('「你直接報個價吧，我很忙。」', -6, 1),
    },
    keyQuestions: ['income', 'goal'],
    ideal: { cash: [3, 4], protect: [4, 5], growth: [1, 3] },
    cards: { legacy: 3, income: 3, medical: 2, accident: 1, care: -2, tools: -2 },
    overNote: { care: '31 歲新手爸爸的優先是家庭責任與收入，長期照顧可以晚點談。', tools: '受雇工程師沒有營業設備風險。' },
    objection: objection('「ETF 長期報酬比保險好太多了吧？」',
      ['投資照樣留著長期成長；保障的工作是讓房貸在你無法工作時繼續繳，ETF 不必在低點被賣掉。', '你沒有否定投資，而是分工', '把投資與保障放在不同角色，客戶更容易接受。'],
      '如果你半年無法工作，房貸和奶粉錢要從哪裡來？',
      '小孩這麼小你還不買保障，太不負責任了。',
      '這個方案的報酬保證比 ETF 還好。'),
    stress: [
      ev(1, 'income', '收入', '過勞住院，留職停薪三個月', '家中暫時沒有收入。', ['income', 'medical'], '收入防線接住了房貸與生活費。', '家豪在低點賣出 ETF 付房貸。'),
      ev(30, 'income', '家庭', '家庭責任測試：主要收入者重大傷病', '需要長期確保房貸與孩子的生活。', ['legacy', 'income'], '家庭責任防線讓太太不必立刻回職場。', '家庭被迫賣房搬家。'),
      ev(55, 'market', '市場', '科技股修正 25%', 'ETF 帳面大幅縮水。', [], '有預備金，不必在低點賣出。', '為了付帳單，他在低點賣出部分 ETF。'),
    ],
  }),
  client({
    id: 'shufen', name: '吳淑芬', short: '淑芬', age: 45, gender: '女性', job: '會計主管', tag: '三明治世代', difficulty: '進階',
    goal: '同時照顧父母與兩個孩子', amount: 'NT$ 1,500,000', incomeInfo: '月薪 9 萬，先生月薪 7 萬', family: '已婚，兩個國中孩子，父親 78 歲',
    intro: '淑芬上有年邁父母、下有孩子，家庭支出龐大。她最近發現父親開始需要人照顧。',
    quote: '「我每天都在處理別人的事，自己的規劃早就沒時間想了。」',
    facts: [['父親的拐杖', '父親去年跌倒後行動變慢。', '長期照顧需求正在浮現'], ['補習班收據', '兩個孩子的補習費每月兩萬。', '子女教育支出'], ['退休試算表', '她曾試算退休金但一直沒完成。', '自己的退休規劃被延後']],
    answers: {
      income: a('「家裡每月固定支出十二萬，我的薪水佔一半以上。」', 7, 11, '收入中斷時的固定支出'),
      goal: a('「我希望爸爸有人照顧，但不能拖垮孩子的教育和我的退休。」', 10, 13, '最不能犧牲的目標'),
      coverage: a('「爸爸那一代幾乎沒有保障，照顧費都要我們出。」', 8, 13, '照顧責任的保障缺口'),
      risk: a('「退休金可以放一些在市場，但孩子的學費不行。」', 5, 9, '風險承受度'),
      premium: a('「我是會計，你直接說重點，不要繞。」', -5, 2),
    },
    keyQuestions: ['goal', 'coverage'],
    ideal: { cash: [3, 4], protect: [3, 4], growth: [2, 3] },
    cards: { care: 3, legacy: 2, medical: 2, income: 1, accident: 0, tools: -2 },
    overNote: { tools: '淑芬是受雇主管，沒有營業設備風險。' },
    objection: objection('「爸爸的照顧費我們兄弟姊妹會分攤，不需要再準備。」',
      ['分攤很好；方案的照顧準備是確保分攤出現落差時，孩子的學費和你的退休金不必被挪用。', '你尊重家庭安排，也補上落差', '承認既有安排，把準備定位成落差緩衝。'],
      '如果照顧需要十年、每月四萬，兄弟姊妹都能穩定分攤嗎？',
      '照顧一個長輩會拖垮全家，你現在不準備一定會崩潰。',
      '有了這個方案，爸爸的照顧費保證完全不用你出。'),
    stress: [
      ev(1, 'cash', '照顧', '父親中風，需要全天照顧', '每月照顧費約四萬元。', ['care'], '照顧準備承接了大部分費用。', '淑芬動用退休金支付照顧費。'),
      ev(30, 'income', '收入', '淑芬因照顧壓力請長假', '收入減少一半持續三個月。', ['income', 'medical'], '收入與醫療防線讓家庭支出照常。', '孩子暫停補習，家庭關係緊繃。'),
      ev(60, 'market', '市場', '股市下跌 20%', '退休金帳面縮水。', [], '退休資產有時間等待回升。', '為了付照顧費，在低點賣出退休資產。'),
    ],
  }),
  client({
    id: 'wenjie', name: '鄭文傑', short: '文傑', age: 58, gender: '男性', job: '國中教師', tag: '退休準備型', difficulty: '進階',
    goal: '兩年後退休，與太太環島旅行', amount: 'NT$ 2,000,000', incomeInfo: '月薪 7 萬，退休後有月退俸', family: '已婚，子女皆已工作',
    intro: '文傑即將退休，退休金看似穩定。他最近被朋友推薦高配息商品，想把退休金拿去「錢滾錢」。',
    quote: '「我有月退俸，生活應該沒問題，剩下的錢想多賺一點。」',
    facts: [['健康檢查報告', '血壓與血糖都在臨界值。', '醫療與照顧風險上升'], ['高配息 DM', '桌上放著標榜年配息 8% 的廣告。', '可能追逐高風險商品'], ['環島地圖', '已規劃退休後的旅行路線。', '退休生活目標']],
    answers: {
      income: a('「月退俸夠生活，但如果生病要自費，那就不一定了。」', 7, 11, '退休後的支出缺口'),
      goal: a('「我只希望退休後不要變成孩子的負擔。」', 10, 13, '最不能犧牲的目標'),
      coverage: a('「公保退休後就沒了，現在只有健保。」', 8, 12, '退休後的保障缺口'),
      risk: a('「朋友說高配息很穩，我想放一半進去。」', 6, 13, '風險承受度與期限'),
      premium: a('「我退休了收入會變少，你還要我花錢？」', -8, 1),
    },
    keyQuestions: ['goal', 'risk'],
    ideal: { cash: [4, 5], protect: [3, 4], growth: [1, 2] },
    cards: { care: 3, medical: 3, accident: 1, income: -1, legacy: -1, tools: -3 },
    overNote: { income: '即將退休、有月退俸，收入中斷防線不是重點。', legacy: '子女已獨立，家庭責任防線屬於過度配置。', tools: '教師沒有營業設備風險。' },
    objection: objection('「高配息每年 8%，比保險划算多了。」',
      ['配息不等於報酬，本金也可能下跌；我們把退休後確定要用的錢和可以承擔波動的錢分開，醫療和照顧另外準備。', '你拆解了「高配息」的迷思', '用期限與用途分配資金，比單純比報酬更專業。'],
      '如果本金跌了兩成，旅行和醫療費還付得出來嗎？',
      '退休族被騙的新聞那麼多，你不聽我的一定會被騙。',
      '這個商品保證每年配息 8%，本金不會虧。'),
    stress: [
      ev(1, 'cash', '醫療', '心血管手術與自費耗材', '一次需要約十五萬元。', ['medical'], '醫療防線與預備金承接了自費。', '文傑動用旅行基金，環島計畫取消。'),
      ev(40, 'cash', '照顧', '術後需要居家照顧半年', '每月照顧費約三萬元。', ['care'], '照顧準備讓太太不必獨自承擔。', '照顧費壓力轉到子女身上。'),
      ev(80, 'market', '市場', '高收益債市場重挫', '高配息商品淨值下跌 18%。', [], '退休資產配置保守，影響有限。', '本金大幅縮水，退休生活被迫縮減。'),
    ],
  }),
  client({
    id: 'yiting', name: '蔡依婷', short: '依婷', age: 24, gender: '女性', job: '行銷專員（社會新鮮人）', tag: '小資起步型', difficulty: '入門',
    goal: '一年內存到第一桶金十萬', amount: 'NT$ 100,000', incomeInfo: '月薪 3.3 萬', family: '單身，與家人同住',
    intro: '依婷剛出社會，預算很小。親戚推銷她一張高額的終身型保單，她很困惑。',
    quote: '「親戚說要趁年輕買，越早越便宜，可是一個月要五千……」',
    facts: [['薪資單', '月薪三萬三，扣除後實領兩萬九。', '預算有限'], ['信用卡帳單', '上個月有一筆旅遊分期。', '緊急預備金不足'], ['親戚給的建議書', '一張每月五千元的終身型保單。', '可能過度配置']],
    answers: {
      income: a('「我住家裡，每月固定支出大概一萬五，其他都是娛樂。」', 7, 10, '固定支出'),
      goal: a('「我想先存到十萬，有一點安全感。」', 9, 12, '最不能犧牲的目標'),
      coverage: a('「爸媽小時候幫我買過醫療險，但我不知道還有沒有效。」', 7, 12, '現有保障盤點'),
      risk: a('「我完全不懂投資，怕賠錢。」', 4, 6, '風險承受度'),
      premium: a('「我也不知道……親戚說五千是基本？」', 2, 4),
    },
    keyQuestions: ['goal', 'coverage'],
    ideal: { cash: [4, 5], protect: [2, 3], growth: [2, 4] }, overProtect: 3,
    cards: { medical: 3, accident: 2, income: 1, legacy: -3, care: -3, tools: -2 },
    overNote: { legacy: '依婷沒有扶養責任，高額家庭責任防線不適合她。', care: '24 歲預算有限，長期照顧不是現階段優先。', tools: '受雇員工沒有營業設備風險。' },
    objection: objection('「我是不是應該聽親戚的，買那張五千元的保單？」',
      ['先盤點你已經有的保障，再用適合預算的方式補上醫療與意外缺口；緊急預備金存到位，比一次買滿更重要。', '你保護了她的預算與目標', '依預算與需求排序，而不是一次推到最滿。'],
      '如果每月繳五千，你的十萬目標要延後多久？',
      '年輕人不買保險，以後生病就會拖累爸媽。',
      '我推薦的這張保證比親戚那張划算一倍。'),
    stress: [
      ev(1, 'cash', '醫療', '急性盲腸炎開刀', '自費與住院約四萬元。', ['medical'], '醫療防線與預備金接住了費用。', '她刷卡分期，存錢計畫歸零。'),
      ev(20, 'income', '意外', '下樓梯扭傷，請假兩週', '請假扣薪約一萬五。', ['accident', 'medical'], '意外防線補上了損失。', '依婷向爸媽借錢周轉。'),
      ev(50, 'market', '市場', '股市小幅震盪', '投資部位短暫下跌 8%。', [], '投入金額適中，她沒有恐慌賣出。', '她恐慌賣出，從此不敢投資。'),
    ],
  }),
  client({
    id: 'zhiwei', name: '林志偉', short: '志偉', age: 40, gender: '男性', job: '小吃店老闆', tag: '自營商家型', difficulty: '進階',
    goal: '五年內開第二家分店', amount: 'NT$ 1,800,000', incomeInfo: '月營業額 30 萬，淨利約 8 萬', family: '已婚，一個國小孩子，太太在店裡幫忙',
    intro: '志偉的小吃店生意很好，全家收入都綁在這家店。他覺得只要店開著就沒問題。',
    quote: '「我店裡生意好得很，錢放在店裡周轉最實在。」',
    facts: [['老舊的瓦斯爐', '爐具用了十年，上個月才修過。', '設備故障可能導致停業'], ['夫妻同店', '太太負責收銀與備料。', '家庭收入集中在單一來源'], ['分店估價單', '第二家店的裝潢估價 180 萬。', '擴張目標資金']],
    answers: {
      income: a('「店停一天就少一萬多，房租和員工薪水還是要付。」', 8, 13, '營業中斷時的固定支出'),
      goal: a('「開分店是我這輩子最想做的事。」', 8, 10, '最不能犧牲的目標'),
      coverage: a('「店裡沒有保什麼，我自己只有勞保。」', 7, 13, '營業與個人保障缺口'),
      risk: a('「我不懂股票，錢都在店裡和存款。」', 4, 6, '風險承受度'),
      premium: a('「做生意的人最討厭推銷，你直接講要多少。」', -7, 1),
    },
    keyQuestions: ['income', 'coverage'],
    ideal: { cash: [4, 5], protect: [3, 4], growth: [1, 2] },
    cards: { tools: 3, income: 2, medical: 2, legacy: 1, accident: 1, care: -2 },
    overNote: { care: '40 歲老闆的優先是營業中斷與收入，長期照顧之後再談。' },
    objection: objection('「錢放在店裡周轉，比買保障有用。」',
      ['周轉金留在預備；保障負責的是店因為設備或人生病停業時，房租和員工薪水不會吃掉分店資金。', '你把保障說成營運工具', '用商家熟悉的語言說明，客戶更容易接受。'],
      '如果瓦斯爐出事停業一個月，房租和員工薪水從哪裡來？',
      '做小吃的火災那麼多，你不保一定會出事。',
      '照我的規劃，五年後保證開得成分店。'),
    stress: [
      ev(1, 'income', '營業', '廚房設備故障，停業三週', '營收歸零，房租與薪資照付。', ['tools', 'income'], '營運防線撐過停業期。', '志偉動用分店資金付房租。'),
      ev(30, 'cash', '醫療', '志偉燙傷住院', '自費與代班人力約八萬元。', ['medical', 'accident'], '預備金與醫療防線吸收了費用。', '只能借高利貸周轉。'),
      ev(60, 'market', '市場', '食材價格上漲 15%', '毛利被壓縮，現金流變緊。', [], '預備金讓他有時間調整菜單。', '現金流吃緊，分店計畫延後。'),
    ],
  }),
  client({
    id: 'peishan', name: '何佩珊', short: '佩珊', age: 34, gender: '女性', job: '醫院護理師', tag: '輪班高壓型', difficulty: '入門',
    goal: '兩年後出國進修', amount: 'NT$ 700,000', incomeInfo: '月薪 6 萬（含夜班津貼）', family: '單身，與男友同居',
    intro: '佩珊懂醫療，自認保障很懂，但輪班與搬病人讓她腰傷反覆。她的收入很依賴夜班津貼。',
    quote: '「我是護理師，醫療的事我比你清楚啦。」',
    facts: [['護腰', '長期搬動病人造成腰傷。', '工作能力與收入綁定'], ['夜班表', '夜班津貼佔收入三成。', '收入結構不穩定'], ['留學簡章', '已在準備語言考試。', '兩年 70 萬目標資金']],
    answers: {
      income: a('「沒有夜班津貼就少兩萬，請病假更慘，房租還是要繳。」', 8, 13, '收入中斷時的固定支出'),
      goal: a('「出國進修是我轉職的機會，不想放棄。」', 9, 11, '最不能犧牲的目標'),
      coverage: a('「醫療我有保，但如果腰傷不能上班，好像沒有東西可以補收入。」', 8, 13, '收入保障缺口'),
      risk: a('「進修的錢放一半在基金，跌了會有點緊張。」', 5, 9, '風險承受度與期限'),
      premium: a('「你們業務都只想賺佣金吧。」', -9, 1),
    },
    keyQuestions: ['income', 'coverage'],
    ideal: { cash: [3, 4], protect: [3, 4], growth: [2, 4] },
    cards: { income: 3, medical: 1, accident: 2, care: -1, legacy: -2, tools: -2 },
    overNote: { legacy: '佩珊沒有扶養責任。', care: '34 歲的優先是工作能力防線。', tools: '受雇護理師沒有營業設備風險。' },
    objection: objection('「醫療我都懂，不需要你來教我。」',
      ['你的醫療專業我很尊重；我想補的是另一塊：腰傷不能上班時，收入和進修資金怎麼不被影響。', '你承認她的專業，再指出盲點', '不跟專業人士爭醫療知識，而是聚焦她沒注意的收入風險。'],
      '如果腰傷讓你三個月不能值夜班，進修計畫會怎麼樣？',
      '護理師職業傷害那麼多，你不買一定會後悔。',
      '這個方案保證你兩年後出得了國。'),
    stress: [
      ev(1, 'income', '收入', '腰椎間盤突出，停職兩個月', '無法上班，收入大減。', ['income'], '工作能力防線補上收入。', '進修基金被拿來付房租。'),
      ev(25, 'cash', '現金', '復健與房租同時到期', '一次需要約五萬元。', ['medical', 'accident'], '預備金承接了這筆支出。', '她向男友借錢，關係緊張。'),
      ev(50, 'market', '市場', '基金下跌 15%', '進修資金帳面縮水。', [], '有預備金，不需要在低點贖回。', '她在低點贖回，進修延後。'),
    ],
  }),
  client({
    id: 'chengen', name: '李承恩', short: '承恩', age: 29, gender: '男性', job: '科技公司資深工程師', tag: '高收入集中型', difficulty: '挑戰',
    goal: '35 歲前財務自由', amount: 'NT$ 10,000,000', incomeInfo: '年薪 250 萬，一半是公司股票', family: '單身',
    intro: '承恩收入高，資產幾乎都是自家公司股票。他相信公司會一直成長，覺得保險是「窮人的思維」。',
    quote: '「我公司股票一年漲五成，買保險的錢拿去買股票不是更好？」',
    facts: [['股票帳戶', '八成資產是同一家公司股票。', '資產高度集中'], ['加班餐盒', '每週工作七十小時。', '健康風險被忽略'], ['財務自由試算表', '目標 35 歲存到一千萬。', '積極的長期目標']],
    answers: {
      income: a('「我每月花五萬，其實存款很多，短期沒問題。」', 6, 9, '固定支出'),
      goal: a('「財務自由，35 歲就可以不用為錢工作。」', 7, 9, '人生目標'),
      coverage: a('「公司團保很好，應該夠吧？不過離職就沒了。」', 7, 12, '團保依賴的缺口'),
      risk: a('「我能承受很大的波動，但如果公司股價腰斬……我可能也同時被裁員。」', 8, 14, '集中風險與收入連動'),
      premium: a('「你說說看，什麼保險值得我花錢？」', 0, 3),
    },
    keyQuestions: ['coverage', 'risk'],
    ideal: { cash: [3, 4], protect: [2, 3], growth: [3, 5] },
    cards: { income: 3, medical: 2, accident: 1, legacy: -2, care: -2, tools: -3 },
    overNote: { legacy: '承恩單身，高額家庭責任防線不是優先。', care: '29 歲先處理收入與集中風險。', tools: '受雇工程師沒有營業設備風險。' },
    objection: objection('「保險的報酬率那麼低，根本不值得。」',
      ['保障不是拿來比報酬的；你的收入和資產都綁在同一家公司，保障和預備金是讓你遇到裁員或生病時不必賤賣股票。', '你點出集中風險', '把保障定位成分散風險的工具，而非投資商品。'],
      '如果公司股價腰斬，同時你被裁員，你的計畫還成立嗎？',
      '你這種過勞的人最容易猝死，不買就等著後悔。',
      '照我的配置，35 歲財務自由保證達成。'),
    stress: [
      ev(1, 'income', '收入', '過勞住院後被裁員', '收入中斷四個月，團保同時失效。', ['income', 'medical'], '工作能力防線讓他不必賣股票。', '他在低點賣出公司股票付生活費。'),
      ev(30, 'market', '市場', '公司股價下跌 45%', '資產帳面腰斬。', [], '預備金讓他有時間等待。', '他被迫低點賣出，財務自由延後十年。'),
      ev(60, 'cash', '醫療', '自費新藥治療', '一次需要約十萬元。', ['medical'], '醫療防線承接自費。', '資產再次縮水。'),
    ],
  }),
  client({
    id: 'jiaming', name: '許家銘', short: '家銘', age: 38, gender: '男性', job: '設計公司合夥人', tag: '頂客族型', difficulty: '進階',
    goal: '夫妻倆 55 歲提早退休', amount: 'NT$ 8,000,000', incomeInfo: '夫妻雙薪月入 18 萬', family: '已婚，無子女，養兩隻貓',
    intro: '家銘夫妻決定不生小孩，打算提早退休。他們最擔心的是「老了沒人照顧」。',
    quote: '「我們沒有小孩，老了只能靠自己。」',
    facts: [['退休計畫書', '目標 55 歲退休、移居花蓮。', '長期退休目標'], ['寵物醫療帳單', '貓咪每年醫療費三萬。', '重視生活品質'], ['合夥契約', '公司收入受景氣影響。', '收入有波動']],
    answers: {
      income: a('「我們每月固定支出八萬，公司景氣不好時收入會掉三成。」', 7, 11, '收入波動與固定支出'),
      goal: a('「最怕的是老了生病，沒人照顧又把退休金花光。」', 10, 13, '最不能犧牲的目標'),
      coverage: a('「我們各自有醫療險，但長期照顧完全沒有準備。」', 8, 13, '照顧保障缺口'),
      risk: a('「退休金可以放在市場，我們還有十七年。」', 5, 9, '風險承受度與期限'),
      premium: a('「你先說說看你的專業建議，不要急著報價。」', -3, 2),
    },
    keyQuestions: ['goal', 'coverage'],
    ideal: { cash: [3, 4], protect: [3, 4], growth: [3, 4] },
    cards: { care: 3, medical: 2, income: 2, accident: 1, legacy: -2, tools: 0 },
    overNote: { legacy: '沒有子女需要扶養，高額家庭責任防線不適合。' },
    objection: objection('「長期照顧離我們還很遠，等五十歲再說。」',
      ['退休金照樣保留成長；越早準備照顧，越不需要在老年時把退休金拿去支付照顧費。', '你把照顧準備連回提早退休的目標', '說明時間與成本的關係，而非製造恐慌。'],
      '如果其中一人需要照顧十年，另一人的退休生活會變怎樣？',
      '沒有小孩的人老了最慘，你們現在不準備一定會孤老。',
      '有了這個方案，你們保證 55 歲可以退休。'),
    stress: [
      ev(1, 'cash', '照顧', '太太車禍後需長期復健', '每月照顧與復健費約四萬元。', ['care', 'medical'], '照顧準備讓退休金不必動用。', '退休金被拿來付照顧費。'),
      ev(30, 'income', '收入', '公司失去大客戶', '收入減少四成持續半年。', ['income'], '收入防線與預備金撐過低潮。', '他們暫停退休提撥。'),
      ev(60, 'market', '市場', '全球股市修正 20%', '退休帳戶縮水。', [], '有足夠預備金，不必賣出。', '低點賣出，退休延後五年。'),
    ],
  }),
  client({
    id: 'guohua', name: '楊國華', short: '國華', age: 50, gender: '男性', job: '計程車司機', tag: '高風險職業型', difficulty: '挑戰',
    goal: '五年內還清車貸、供女兒念完研究所', amount: 'NT$ 900,000', incomeInfo: '月收入 4–5 萬，扣油錢與車貸', family: '已婚，女兒念大學',
    intro: '國華開計程車二十年，收入被車貸與油價吃掉一大半。他覺得自己身體硬朗，最近卻常腰痠背痛。',
    quote: '「我開車二十年沒出過大事，保險都是騙人的。」',
    facts: [['車貸單', '新車貸款還有四年。', '營業工具負債'], ['女兒的學生證', '女兒研究所還要兩年。', '教育支出'], ['痠痛貼布', '長時間開車造成腰傷。', '健康與收入連動']],
    answers: {
      income: a('「車停一天就沒收入，車貸一萬五、家用兩萬照付。」', 8, 13, '營業中斷時的固定支出'),
      goal: a('「女兒是我們家第一個念研究所的，一定要供她念完。」', 10, 12, '最不能犧牲的目標'),
      coverage: a('「車子有強制險，我自己只有勞保。」', 7, 12, '個人與營業保障缺口'),
      risk: a('「投資？我哪有閒錢投資。」', 3, 5, '風險承受度'),
      premium: a('「我開一天車才賺兩千，你要我花多少？」', -8, 1),
    },
    keyQuestions: ['income', 'coverage'],
    ideal: { cash: [3, 4], protect: [4, 5], growth: [1, 2] },
    cards: { accident: 3, tools: 3, income: 2, medical: 1, legacy: 1, care: -2 },
    overNote: { care: '國華的優先是意外與營業中斷，長期照顧之後再談。' },
    objection: objection('「保險都是騙人的，理賠的時候一堆理由不賠。」',
      ['你的擔心很合理，所以我們會一起看清楚保障範圍與除外條款；重點是車停時，車貸和女兒學費有人接住。', '你回應了不信任，並強調透明', '承認疑慮、承諾說明條款，是建立信任的合規做法。'],
      '如果車子進廠一個月，車貸和女兒的學費要怎麼辦？',
      '開計程車的出車禍是遲早的事，你不買一定會後悔。',
      '我們公司保證什麼都賠，絕對不會拒賠。'),
    stress: [
      ev(1, 'income', '意外', '路口被闖紅燈撞擊，車輛送修', '人車都需要休養一個月。', ['accident', 'tools'], '意外與營運防線撐住了這個月。', '國華向地下錢莊借錢付車貸。'),
      ev(25, 'cash', '醫療', '腰椎手術', '自費與休養約八萬元。', ['medical', 'income'], '預備金與醫療防線吸收了費用。', '女兒申請助學貸款。'),
      ev(55, 'market', '市場', '油價上漲 20%', '每月淨收入少五千。', [], '預備金讓家計有緩衝。', '家用捉襟見肘。'),
    ],
  }),
  client({
    id: 'yijun', name: '陳怡君', short: '怡君', age: 42, gender: '女性', job: '外商業務經理', tag: '高房貸家庭型', difficulty: '進階',
    goal: '房貸提前還清、兩個孩子出國讀書', amount: 'NT$ 3,000,000', incomeInfo: '年薪 180 萬，獎金佔四成', family: '已婚，兩個孩子，先生是自由工作者',
    intro: '怡君是家中主要收入來源，房貸還有 800 萬。她的收入有四成是業績獎金，波動不小。',
    quote: '「我收入很好，房貸慢慢還就好，不想被保險綁住。」',
    facts: [['房貸合約', '剩餘本金 800 萬、還有 20 年。', '大額長期負債'], ['業績獎金單', '獎金佔年收入四成。', '收入波動'], ['留學資料夾', '計畫讓孩子高中出國。', '大額教育目標']],
    answers: {
      income: a('「房貸每月四萬五，家用三萬，先生收入不固定。」', 8, 13, '收入中斷時的固定支出'),
      goal: a('「最怕我倒下，房子和孩子的教育都保不住。」', 10, 13, '最不能犧牲的目標'),
      coverage: a('「公司團保額度是年薪兩倍，但比房貸少很多。」', 7, 12, '保障缺口'),
      risk: a('「我有一些基金，跌了也還好。」', 5, 8, '風險承受度'),
      premium: a('「我時間很寶貴，直接給我三個方案比價。」', -4, 2),
    },
    keyQuestions: ['income', 'goal'],
    ideal: { cash: [3, 4], protect: [4, 5], growth: [1, 3] },
    cards: { legacy: 3, income: 2, medical: 2, accident: 1, care: -1, tools: -2 },
    overNote: { care: '42 歲的優先是房貸與家庭責任。', tools: '受雇經理沒有營業設備風險。' },
    objection: objection('「公司團保已經是年薪兩倍了，夠了吧？」',
      ['團保很好，但它跟著工作走，額度也少於房貸；我們只補上落差，讓房貸和孩子的教育不會因為你離職或生病而中斷。', '你盤點既有保障再補落差', '不重複投保，只補缺口，最能建立專業信任。'],
      '如果你轉職或被裁員，團保還在嗎？',
      '團保根本沒用，你不另外買全家都會完蛋。',
      '這個方案保證你的孩子一定能出國讀書。'),
    stress: [
      ev(1, 'income', '收入', '景氣下滑，獎金歸零且部門縮編', '收入減少四成持續半年。', ['income'], '收入防線讓房貸照常繳。', '房貸遲繳，信用受損。'),
      ev(30, 'income', '家庭', '家庭責任測試：主要收入者重大傷病', '需要長期確保房貸與教育。', ['legacy', 'medical'], '家庭責任防線保住了房子。', '被迫賣房搬家。'),
      ev(60, 'market', '市場', '基金下跌 20%', '教育基金縮水。', [], '有預備金，不必在低點贖回。', '在低點贖回，留學計畫延後。'),
    ],
  }),
  client({
    id: 'yixiang', name: '高奕翔', short: '奕翔', age: 27, gender: '男性', job: '健身教練（自由接課）', tag: '身體即資本型', difficulty: '入門',
    goal: '三年內開自己的健身工作室', amount: 'NT$ 1,000,000', incomeInfo: '月收入 5–7 萬，依課堂數', family: '單身',
    intro: '奕翔靠身體賺錢，收入完全取決於能上幾堂課。他覺得自己身體最健康，保險是浪費錢。',
    quote: '「我每天運動，身體比誰都好，買保險太浪費了。」',
    facts: [['膝蓋護具', '示範動作讓膝蓋舊傷復發。', '工作能力與身體綁定'], ['學員預約表', '每月上課約 80 堂。', '收入依賴親自授課'], ['工作室估價', '器材與裝潢約 100 萬。', '三年創業目標']],
    answers: {
      income: a('「我一個月固定要付兩萬五，受傷不能上課就沒收入。」', 8, 13, '收入中斷時的固定支出'),
      goal: a('「開工作室是我的夢想，存款絕對不想動。」', 9, 11, '最不能犧牲的目標'),
      coverage: a('「我什麼保險都沒有，健身房也沒有幫教練保。」', 7, 13, '保障缺口'),
      risk: a('「存款都放在高股息 ETF，跌了我也不太在意。」', 5, 8, '風險承受度'),
      premium: a('「你們業務都很會說，我先聽聽看要多少。」', -6, 1),
    },
    keyQuestions: ['income', 'coverage'],
    ideal: { cash: [3, 4], protect: [3, 4], growth: [2, 3] },
    cards: { accident: 3, income: 3, medical: 1, tools: -1, legacy: -2, care: -2 },
    overNote: { tools: '目前還沒有自己的工作室，器材營運防線還太早。', legacy: '奕翔單身，沒有扶養責任。', care: '27 歲的優先是意外與收入中斷。' },
    objection: objection('「我身體這麼好，買保險根本是浪費。」',
      ['你的身體就是你的事業，所以更要保護；保障的角色是萬一受傷，工作室存款不用拿來付生活費。', '你把身體連回他的事業', '用客戶自己重視的價值說明保障。'],
      '如果膝傷讓你兩個月不能上課，工作室計畫會怎麼樣？',
      '運動員受傷是家常便飯，你不買一定會後悔。',
      '照這個方案，保證三年後開得成工作室。'),
    stress: [
      ev(1, 'income', '意外', '示範動作時十字韌帶斷裂', '需要手術與休養三個月。', ['accident', 'income'], '意外與收入防線讓存款完好。', '工作室存款被拿來付生活費。'),
      ev(30, 'cash', '醫療', '手術自費與復健', '一次約九萬元。', ['medical', 'accident'], '預備金承接了這筆支出。', '他刷卡分期，壓力很大。'),
      ev(60, 'market', '市場', '高股息 ETF 下跌 12%', '存款帳面縮水。', [], '不必在低點賣出。', '低點賣出，工作室延後。'),
    ],
  }),
];
